"""empty message

Revision ID: 666bc24e2c2a
Revises: 6ad0f0d482a8
Create Date: 2024-06-12 17:01:53.873218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666bc24e2c2a'
down_revision = '6ad0f0d482a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_generated_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['client_generated_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('client_generated_id')

    # ### end Alembic commands ###
